theme: minima
markdown: GFM
title: KeepReading
#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
nav_pages:
#     - nothing
#
#   Set to `true` to show excerpts on the homepage.
show_excerpts: false
