remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme
markdown: GFM
exclude: ["**/README.md"]
title: KeepReading
author:
  name: EMSPX
  email: support@euromatsoftpolex.com
description: >
  Turn your books into audiobooks. KeepReading - even when you can't read. Photograph the
  pages of any book with your phone, and KeepReading creates a fully navigable audiobook
  complete with auto-detected chapters and progress tracking. Listen while cooking,
  commuting, working out, or doing chores. Your books, finally integrated into your active
  life.

#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
nav_pages:
#     - nothing
#
#   Set to `true` to show excerpts on the homepage.
show_excerpts: false
